### ISSUE TITLE
Change sorting "logic" to allow numbers in titles

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#1007]
Maybe using dots or underscores that don't interfere with the url scheme "01.2012-the-year-of-the-cat" or "20120701_2012-the-year-of-the-cat".

**Comment by jenstornell** [comment]
If I understand you correctly this would solve [this problem](https://forum.getkirby.com/t/kill-the-current-menu-system/1445)? That I with the change can create pages called "30 days" in the panel without a problem even when sorting.

In that case I really really want to see a change. I often run into this issue. Even if it would break "some eggs" I think in the end it would be worth changing it. I see it as a bug.

The dot prefix looks better I think. At the same time I'm not sure if it would add problems in some environments. In windows `.htaccess` files can't be renamed in Windows Explorer for example. But because it does not start with a dot I think it should be ok.

**Comment by texnixe** [comment]
Yes, that is the idea. The files shouldn't start with a dot, of course.
