### ISSUE TITLE
File overview: Items jump around because of incorrect width

### ISSUE THREAD

**Issue by medienbaecker** [getkirby-v2/panel#1041]
At some viewport widths the last file in the file grid will break down to the next row when dragging it.  In all browsers I tested, Chrome, Safari and Firefox. I think it has something to do with the percentage width. Since it's only occurring at some widths here's a GIF demonstrating what I mean:

![imagegrid](https://cloud.githubusercontent.com/assets/7975568/25746154/72de7f72-31a2-11e7-8ff2-6cac17629c39.gif)

As I use the same view in my images field I fixed it by setting the widths to `0.1%` less so it's `49.9%` instead of `50%` and `33.23%` instead of `33.33%`: https://github.com/medienbaecker/kirby-images/commit/1096c5c2ba469738dccfc2cbc635168b7558c98f

**Comment by jenstornell** [comment]
I've had a similar problem on one of my websites. Not sure it it works in this case but I just added more decimals to get it to work, like `33.333333333333%`.

**Comment by lukasbestle** [comment]
I think using `calc` is probably the best way to solve this. But I couldn't even make it work with `calc(100% / 3)`, I needed to use `calc(100% / 3 - 1px)`, which is quite a hack. Let me know if you find a proper solution. :)

**Comment by medienbaecker** [comment]
I don't think it has something to do with the `33.33%` as it also happens with the `25%` media query. There are no decimals in `25%`.

If you look at the DOM while dragging a grid item, you can see there's an added `ui-sortable-placeholder` element. I guess this element introduces whitespace to the code and `display: inline-block` doesn't like that. 

Would flexbox be a solution? The browser support is surprisingly good already: http://caniuse.com/#feat=flexbox

**Comment by lukasbestle** [comment]
I agree that we should probably use Flexbox for this. But I will also look into this some more and try to find a quicker fix (we are working on a new Panel version anyway).

**Comment by lukasbestle** [comment]
It turns out that this doesn't actually have anything to do with the grid system.

If you open your dev tools while dragging, you can see that the grid items (with class `ui-sortable-handle`) get a style attribute with absolute positioning rules. The `left` and `top` values are the ones that are interesting here. In the situations where this bug happens, these values are set incorrectly by jQuery UI.

To be honest I have no idea where to start to debug this. If anyone of you knows the jQuery UI codebase well, feel free to dig into this.
Otherwise, this will be fixed in the new Panel version anyway.
