### ISSUE TITLE
Date popup pops up on save if default is set

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#1090]
Seems to be related to where the focus is, i.e. even if the date field is no longer focused, but focus is not definitely on another field.

**Comment by lukasbestle** [comment]
This is not directly related to the date field. If you save a Panel form, the field that was last focused is focused again. And if that field is a date field, that makes the date field pop up again. So it's a general problem but just more noticeable in the date field.

I'm pretty sure the issue is [in the focus component](https://github.com/getkirby/panel/blob/2.5.6/assets/js/src/components/focus.js#L40). The new focus is stored once a field is focused or the caret changes, but not "forgotten" once the field is blurred. A simple `on('blur')` won't work however as the field is also blurred by clicking on the save button. So we basically need to detect if the blur event happened because of clicking on the save button or because of clicking on the whitespace around the form. @distantnative?
