### ISSUE TITLE
Spaces at the beginning and the end of fields get removed

### ISSUE THREAD

**Issue by tweh** [getkirby-v2/panel#322]
I guess it’s the desired behavior that spaces at the beginning and the end of fields get trimmed for the output but sometimes it would be handy to switch this off, e.g. of a filed to store a unit or the separator in the page title. Maybe you can add a `trim:false` option for the blueprints.

**Comment by bastianallgeier** [comment]
The trim: false option is a fantastic idea!! I will keep this in mind for one of the next versions.

**Comment by tweh** [comment]
Are there any news about this issue? At the moment I can’t us the panel for some of my pages (i.e. [my blog containing code examples](http://tobiw.de/tbdm/tikz-adventskalender)) because it destroys indention …

I postet also a quoestion in the forum (cause I forgot that I already posted this issue …): [Prevent Panel from stripping spaces](https://forum.getkirby.com/t/prevent-panel-from-stripping-spaces/2811?u=tobiasweh).

**Comment by lukasbestle** [comment]
This is a different issue. Your issue with the builder field is that indentation in the middle of the field content is broken, not that indentation at the beginning/end is lost.

Also if I think about this, this beginning/end anti-trimming feature can't really be implemented with a blueprint option only, because when the Kirby core loads the content file, it will trim the value as well. And because the core does not parse blueprints, it won't know about that.

**Comment by tweh** [comment]
OK … I see there’s a difference, but to be clear the issue with “mid-spaces” affects `structure` fields as well … should I open a new issue for that?

Didn’t know the handling of leading/trainling space in the core. In that case maybe some automatic adding of a line start/end character sequence could be helpful … (like my use of `∆` as described in the forum)

**Comment by jenstornell** [comment]
**Moved from a duplicate issue:**

It's sometimes needed to keep the spaces in the beginning of a textarea for some custom form fields. Read more about the issue here:

https://forum.getkirby.com/t/allow-spaces-in-the-beginning-of-a-textarea-in-the-panel/3594

Now the spaces in the beginning of a textarea is stripped out.

### Possible solution

In this case I don't like the idea of having an option for it in the blueprint because it should be handled by the field itself. Instead I would like it to be a data attribute (or similar) with information about it.

```html
<textarea data-allow-whitespace="true"></textarea>
```

If the panel sees this, it will allow spaces on that field.

**Comment by lukasbestle** [comment]
It's not that easy unfortunately as I wrote above. The core will trim the field again when loading from the text file. So not saving is the issue but loading.

**Comment by distantnative** [comment]
> @lukasbestle:
> It's not that easy unfortunately as I wrote above. The core will trim the field again when loading from the text file. So not saving is the issue but loading.

Is that also the case if the content would be saved this way?

```

----

Text: " space at start and end "

----

```

**Comment by lukasbestle** [comment]
No, but then the core would need to strip the quotes (or whatever character we decide to use). What happens if the user intended to use quotes at the beginning/end of their fields?

**Comment by jenstornell** [comment]
@lukasbestle Can't the core just remove the first and last character in the case with quotes? Then it does not matter what the user uses in between.

For it to work there need to be a blueprint option so make the core know that it should remove the quotes.

**Comment by lukasbestle** [comment]
No, because then users who edit their content manually or users with content that was saved before the change will get content that has two characters less than intended. ;)

Again: The core doesn't know *anything* about blueprints and this won't be changed for performance reasons as stated before. We can't make this depend on a blueprint option.

**Comment by jenstornell** [comment]
I was thinking wrong, sorry about that.

The only thing I can think of is a protected character combination that will be replaced, no matter of what's in the blueprint, something like this:

**In the panel:**

```
  Space at start and end  
```

**Saved in the content:**

```
Text: [space][space]Space at start and end[space][space]
```

**Output:**

```
  Space at start and end
```
