### ISSUE TITLE
Minumum and maximum files number validation

### ISSUE THREAD

**Issue by afbora** [getkirby-v2/panel#378]
Following feature is possible? Minumum files(images) number required or limit user to upload maximum files number.
### Sample blueprint:

```
files:
    min: 1
    max: 10
```

**Comment by lukasbestle** [comment]
Setting a maximum could work, but a minimum is quite difficult to implement. It depends on how to define "minimum". A possible interpretation could be "the page can't be set to visible until there is at least one file". But what happens if the user deletes the file again? It should automatically make the page invisible, but that adds quite a lot of complexity.

**Comment by byybora** [comment]
I understand that implement is a little complex. 

When user try to delete the file, system can checks validation before deleting. A idea! ;)

**Comment by lukasbestle** [comment]
Ah, so if you wanted to replace a file you would upload a new one and then delete the old one. That could work, yes.

**Comment by byybora** [comment]
File replacing feature Kirby already has. User doesnt have to delete it. Just replace it!

**Comment by lukasbestle** [comment]
I totally forgot about that. You are right!

**Comment by bastianallgeier** [comment]
The max setting is already available. The min setting seems to involve quite a lot of additional thinking. I will keep this on the ideas list.

**Comment by iksi** [comment]
The max setting doesn’t seem implemented (`canHaveMoreFiles()` is not called).
