### ISSUE TITLE
Make visible if field content comes from another language

### ISSUE THREAD

**Issue by tweh** [getkirby-v2/panel#437]
I just made up my first multi language project with kirby and noticed the the filed of al non-default languages are set to the content of the default language, if they are empty. It would be nice is the panels shows that the content is inexplicit e.g. by showing the text in grey instead of black.

**Comment by distantnative** [comment]
This isn't really possible easily for the panel, since all missing fields from the current language are replaced with values from the default language already in the Kirby core Page object. So the panel can't really know which value is taken from the default language and which is actually specified for the specific language :/ Tho I do see why that would be nice to have.

**Comment by tweh** [comment]
Ahh … thanks I didn’t know these internals …
