### ISSUE TITLE
Remove user fields: First Name / Last Name

### ISSUE THREAD

**Issue by samnabi** [getkirby-v2/panel#682]
Now that we have the ability to do custom user fields in the panel, I propose we get rid of First Name / Last Name as required default fields. Let developers choose a name input structure intentionally, if they need one.

This will help with internationalization and accommodate people with different name structures.

Follow-up to this discussion: https://forum.getkirby.com/t/more-flexible-name-structures-in-the-panel/2614

**Comment by bastianallgeier** [comment]
Interesting points. I will definitely consider this.

**Comment by JimmyRittenborg** [comment]
:+1:

**Comment by samnabi** [comment]
Would it be possible to consider this for 2.4.1?

**Comment by LeBenLeBen** [comment]
I have another use case which could be solved by removing those fields, or more precisely being able to create them myself with my own field settings.

I’m creating users on-the-fly from a third-party system and I’ll automatically import first name and last name. Therefor I’ll like to set "readonly: true" on them in the blueprints. At the moment it’s not possible because default fields settings are just ignored.
