### ISSUE TITLE
Support snippets in place of structure entries

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/panel#747]
See [this post](https://forum.getkirby.com/t/using-kirby-s-power-in-entry-of-structure-field/1044/5?u=lukasbestle).

**Comment by jenstornell** [comment]
+1

**Comment by lukasbestle** [comment]
Also see [this post](https://forum.getkirby.com/t/page-builder-multiple-images/3303/8?u=lukasbestle).

**Comment by samnabi** [comment]
How does this work with multi-language sites? Can we pass the panel language to the snippet so it knows which string to output?

**Comment by lukasbestle** [comment]
The entry does currently not support languages either, but yes, good point. Either that or one snippet per language (like titles, help texts etc.).

**Comment by distantnative** [comment]
What do you think where these should go? `blueprints/snippets/`? Normale `snippets` directory?

**Comment by jenstornell** [comment]
**Good about having it in the normal snippets folder:**

- It's a common user pattern to use that snippet folder for everything.
- It adds no extra stuff to think of. It's there already.

**Good about having it in blueprints/snippets/:**

- It's closer to blueprints which means less fiddling around folder structure.
- It will separate these snippets from other snippets. Better organisation by design.
- If in the future will be a way to have more plugin package that containing fields and blueprints in the plugin folder, then it would fall naturally to that package.

Which way is the best? I don't know. Both have their ups and downs.

**Comment by texnixe** [comment]
I think this should go into a blueprints/snippets folder, not into the normal snippets folder to separate panel stuff from templating.

**Comment by distantnative** [comment]
Okay, also wondering if `snippets` is the right term for it. So to not confuse them with the stuff from `blueprint/fields`

**Comment by lukasbestle** [comment]
I agree to put them into the `site/blueprints` dir, but I also agree that the name shouldn't be `snippets`. No idea what else to use though, the term `snippets` by itself is pretty great if there weren't blueprint snippets.

**Comment by jenstornell** [comment]
Maybe "parts" or "entries"?

**Comment by texnixe** [comment]
I would also suggest "entries", makes it clear that it relates to the entry option in blueprints.

**Comment by distantnative** [comment]
Yea, I like `blueprints/entries/. We still would need to decide
1. how to specify in the blueprint for `entry:` and `help:` the reference file
2. how to use variables in these entries and what variables get passed to these entries

**Comment by jenstornell** [comment]
Maybe something like this?

```yaml
entry:
    file: my-entry.php
    variables:
        - First
        - Second
        - {{filename}}
```

**Comment by jenstornell** [comment]
I think it would be nice to have access to a `$page` object as well as a `$field` object into the snippet, without the need to send it every time.

Very often you probably want to build something that rely on the page or the field.

In that case there would probably be less {{inline_variables}} in the entry which makes it cleaner.

**Comment by lukasbestle** [comment]
But what about #770? If we choose "entries" it doesn't fit to the help texts in my opinion. Maybe something like "labels"?

**Comment by jenstornell** [comment]
For me a label is just a short text, but when thinking about it, this feature is a kind of an advanced label.

I don't think `labels` is a fantastic name for it, but if there are no better suggestions, then I'm fine with it.

**Comment by texnixe** [comment]
For the help text, label might make sense, but in the context of entry snippets, I find it rather irritating.

**Comment by lukasbestle** [comment]
Well, a structure entry is also "labeled" by the YAML template or the PHP snippet.

Maybe we can find a word that fits both, but I think we should to avoid having either two directories or one with a name that only fits one feature of the two (maybe more fields will support these kind of snippets in the future, and then it will be even more difficult to understand).

**Comment by jenstornell** [comment]
**Other suggestions:**

- descriptions
- presentations
- outputs
- visuals

**Comment by jenstornell** [comment]
**I just got what I think is brilliant name for it:**

```
spoilers
```

I've seen it in the [Calendar Board](https://github.com/molocLab/kirby-calendar-board/issues/16) plugin and I think it's a great name.

What do you think?

**Comment by samnabi** [comment]
What about "previews"? Since the `entry` field is essentially a preview of your structure item.

**Comment by lukasbestle** [comment]
I like "presentations" (or maybe "presenters"?). This term fits to everything that gets displayed in the Panel as a preview or help text.

**Comment by samnabi** [comment]
On second thought, "previews" doesn't apply very well to help text. "Spoilers" sounds a little goofy to me.

I think a `blueprints/snippets` folder makes sense. We're used to putting PHP code in the main snippets folder, and `blueprints/fields` stands on its own as a place for YAML content.

**Comment by jenstornell** [comment]
@samnabi 

One downside of having both folders called `snippet` is that in Sublime Text we can add folders to the project and if both snippets folders are added, they would look exactly the same. It would be impossible to spot the difference.

Another pitfall is that when moving stuff to the `snippets` folder, the chance is bigger that it ends up in the wrong `snippets` folder. The chance might be low but higher than before, because of that name.

A plugin might for example have a `snippets` folder. Is it the `blueprints/snippets` or is it the `site/snippets`? The plugin creator will need to put another folder in the root to show what kind of snippet it is.

Other than those things I think `snippets` is the most correct word for it. There seems to be no synonyms.

**Comment by jenstornell** [comment]
**Synonyms to snippets:**

Translated from Swedish:

- bits
- fragments

**Comment by texnixe** [comment]
We might as well use a compound like panel-snippets or field-snippets to avoid having the same folder name in different sections.

**Comment by jenstornell** [comment]
@texnixe Yes, why not? Then we can name everything the same as in site, whenever is needed, but still prevent the "conflict" I talked about. And we don't need to figure out new names for everything.

**Comment by jenstornell** [comment]
https://github.com/jenstornell/kirby-snippetfield

I could not wait for it.
