### ISSUE TITLE
Prevent closing of structure field modal when uploading files

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#755]
See this [forum suggestion](https://forum.getkirby.com/t/dont-close-modal-on-upload/3193)

When uploading a file via drag & drop the structure field modal is closed and all content lost.

**Comment by distantnative** [comment]
It's closed since the whole page is reloaded to show the uploaded file. So we could approach this in different ways:

- If a modal is open, don't do the reload. Modal and its content will be preserved but in the modal you would not see the new file e.g. in a file select.
- If a modal is open, try to apply it before reloading the page. Then re-open the modal. Problem would be that this actually applies changes to the page and saves them. This could already cause problems with structure field modals but think about other modals such as delete or change url.

So I'm not sure how to solve this best.

**Comment by texnixe** [comment]
Of the two options, the first seems to be more reasonable. It would give the user a chance to either save the changes and then to reopen the modal to select an image.

One more reason to move away from using modals for structure fields.

**Comment by lukasbestle** [comment]
I think the issue with this solution is that most of the time the uploaded file is supposed to be used immediately in a select field for example. If it is not there, that can be confusing. But yes, better than losing the structure field content.

Maybe we could display a warning to let the user know it has been uploaded but is not yet available in the fields.

**Comment by distantnative** [comment]
I mean a not so trivial change would be, that the Uploader checks if a modal is open before actually uploading and reloading.

If a modal is open, it stores the state and the current modal content in a separate session – not the one that is representing the field contents to not overwrite them. Then, on a page load the panel would need to check if such a modal store session exists and if yes, restore it with its contents. That way, the modal would not disappear on upload, the modal field contents would be still the same as before the upload, but no changes from the open modal would be applied to either the content file or the content store session.

**Comment by lukasbestle** [comment]
That would definitely be a proper fix.

I think this is a good idea anyway if the browser window is closed by accident etc.
There is already a mechanism for the main form, one for the modals would be great.

**Comment by texnixe** [comment]
Sounds reasonable. 

How would this then relate to #688?

**Comment by distantnative** [comment]
It would relate to #688 in a way that we would need to prevent the bug present in the current main content sesstion store for such a modal store as well.
