### ISSUE TITLE
Smiley-face on top over language switcher

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#765]
When using multiple languages and save I want to make sure the other translations of the pages are correct. But just when I want to switch language the smiley-face appear, covering the switcher.

I know I can close it but it disturbs the workflow a bit.

Maybe make the smiley-face push the language switcher to the left instead?

![image](https://cloud.githubusercontent.com/assets/927011/12888767/d95fe816-ce7b-11e5-9c1e-23846d4fbad5.png)

**Comment by malvese** [comment]
Just wondered why it is in the topbar, as it is very far from the Save button we just clicked. We can use the shortcut, but since the save button is never hidden wouldn't it give a bit more context to group them?
Pretty much like when we have unsaved changes actually.

![saved](https://cloud.githubusercontent.com/assets/193492/12942873/011b61e2-cfde-11e5-9c31-c19336dd2ad3.png)

**Comment by jenstornell** [comment]
Yes why not. I also feel it does not belong to the top menu naturally. +1

**Comment by malvese** [comment]
Unless there are secrets plans for a broader notification system in the topbar ;)

**Comment by bastianallgeier** [comment]
To me it clearly belongs in the topbar. It's already a global notification system, which is also used for uploads, sorting and other stuff. In those cases there's no clear position where the notification would belong to and so in my opinion it makes much more sense to have one clear spot for it.

**Comment by jenstornell** [comment]
Then it would probably be a bad idea to change the whole notification system then.

Maybe just move the language selector to the left?

![image](https://cloud.githubusercontent.com/assets/927011/12944659/dd1598b6-cfe8-11e5-9b12-d321202f17b6.png)
