### ISSUE TITLE
$page->uri('language-code') does not work in custom field

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/panel#805]
See [this thread in the forum](https://forum.getkirby.com/t/get-default-language-uri-from-object-in-the-panel/3545/4)

**Comment by distantnative** [comment]
Workaround that should work in custom field / panel:

```php
kirby()->site()->page($this->page->uri())->uri($languageCode)
```

**Comment by jenstornell** [comment]
I can comfirm that the workaround work like the uri on the frontend.

**Suggestions for solution:**

1. `$page->uri()` in the panel and the frontend does different things. Keep them apart by for example add the `$page->panelUri()`. Don't mix them together in a single function.
1. Change the `$page->uri()` when inside a field.

I like suggestion 1 better because it feels long term and not hackish. Solution 2 means kind of hack the page uri just for a field.

**Comment by lukasbestle** [comment]
Another possible solution: Make the `$field->page()` method return a "normal" Kirby page in the first place. I don't know however if that would limit fields in another way.

**Comment by distantnative** [comment]
> Another possible solution: Make the $field->page() method return a "normal" Kirby page in the first place. I don't know however if that would limit fields in another way.

I think this could break a few existing fields. But another thought: If it's only about the default language uri, I think `$this->page->id()` should do the job, shouldn't it?

**Comment by jenstornell** [comment]
@distantnative What I don't like about it consistancy. If the page object in the panel acts differently than on the frontend, then we need to learn two kind of page objects instead of one depending on where we are. That will probably generate more questions in the forum as well.

Whatever solution, I vote for that the page object acts the same on frontend and in the panel.

Then if the page object in the panel should have some extra functions, it's fine. Just that the common functions stays the same. That page->uri() works the same. That would be expected.

**Comment by jenstornell** [comment]
I just want to say that this function does not work in all cases:

```
kirby()->site()->page($this->page->uri())->uri($languageCode)
```

When switching language it does not always work (don't remember exactly when). Just try it well before implement.

**My latest workaround looks like this:**

https://github.com/jenstornell/kirby-seo/blob/master/fields/seo/template.php

```
$code = site()->defaultLanguage()->code();
$page_uri = str_replace( '/' . $code, '', $page->uri( $code ) );
```

I have this issue from time to time so for me it's not so edge case.

Maybe you can look into the [38 existing custom form fields](https://github.com/jenstornell/kirby-plugins/labels/Field) and search for `page->uri()` and see if you break any of them?

If not, then change the behaviour of the `page->uri()`.

**Comment by distantnative** [comment]
> Maybe you can look into the 38 existing custom form fields and search for page->uri() and see if you break any of them?

I am much more afraid of breaking a lot of the panel :laughing:

**Comment by jenstornell** [comment]
**I would do this:**

### 1. Add a new function

Add a new function like `$this->page->panelUri()`, a copy of the current panel `$this->page->uri()` function.

### 2. Search replace

Search replace all `$this->page->uri()` to `$this->page->panelUri()` in the panel.

### 3. Fix page->uri()

Fix `$this->page->uri()` so that it returns the same as on the frontend. It will then do nothing to the panel because that function is no longer used. Instead all the future fields does not need to hack the page uri anymore.

### 4. Test the panel

Nothing should be broken because panelUri is used instead.

**Comment by jenstornell** [comment]
@distantnative Now I'm having this issue again and I got your fix working.

```php
echo kirby()->site()->page($this->page->id())->uri($languageCode);
```

It should be id instead of uri to make it work. So far I have not been able to break it.
