### ISSUE TITLE
User language codes in different format

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#818]
Most of the user languages in the select box uses the short version of the language codes, but some uses the longer version. It's a little inconsistent to mix them like this.

```
ar
bg
ca
cs
da
de
en
es_419
es_ES
fa
fi
fr
hu
id
it
ja
nb
nl
pl
pt_BR
pt_PT
ro
ru
sv_SE
tr
zh_CN
zh_TW
```

**Comment by lukasbestle** [comment]
The reason for this is Transifex, where the Panel is translated. They use these codes as far as I can tell.

BTW: It is required to do it like this actually because all affected languages have different variants. Brazilian Portuguese is different from Portuguese for example, but both are variants of the same language.

**Comment by jenstornell** [comment]
I understand why they need 5 characters but then shouldn't all of them use that to be consistant?

**For example:**

```
en
```

**Should be:**

```
en_GB
```

Then they would all be the same format, like this:

```
en_GB
sv_SE
```

(short list, I know)

**Comment by olach** [comment]
I would propose @lukasbestle to re-open this issue. I just encountered this inconsistent behavior when translating form fields in blueprints. It would be better to have consistent naming for the languages.

The issue was closed because of this reason:
> The reason for this is Transifex, where the Panel is translated. They use these codes as far as I can tell.

But in Transifex you should be able to specify the language codes with a locale. Look at this page for example:
https://www.transifex.com/explore/languages/

If we'll always be using the full language code, we'll make sure that this is future proof.

But, even if we go this route with full language codes or not, I think we still need to support the short version in blueprints. Imagine that translations for `de_DE` and `de_CH` is available. By using the full language code we can specify the exact translation. But using the short version `de`, a fallback translation should be used. Either a specified fallback or the first available translation of the country.

Right now I'm building a site with three languages. When translating blueprints I need to use these language codes: `en`, `de` and `sv_SE`.

The expected behavior would be to use full language codes for all languages. But it would also be nice to be able to use the short version. I.e: `sv` would map to `sv_SE` automatically if `sv` is not found, but `sv_SE` is.

**Comment by lukasbestle** [comment]
We can't really use full codes for all languages. Some translations might be fitting for multiple variants (the German one for example should be alright for Austria and Switzerland, it's not too different).

But I agree that we should support setting field translations with the "general" code and allow overrides for variants. Seems like a good idea.

**Comment by olach** [comment]
Sounds good to me!

**Comment by lukasbestle** [comment]
We should also definitely clean up the localizations for v3.
