### ISSUE TITLE
Don't override the refresh key (F5) on Windows

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/panel#856]
> ... Could we please change the keyboard shortcut away from "F5"? 
> "F5" in Windows is like "Cmd + R" on mac (refresh page). I think overriding the refresh key (with something that doesn't refresh the page) isn't that user friendly

More here:

https://forum.getkirby.com/t/changing-templates-in-panel-super-nice-but/4281

**Comment by rasteiner** [comment]
Oh, now that I know that it's a bug and not intended behaviour, here something I've noticed: 
It seems to happen only when no form element (a textbox, textarea, select, etc) is selected.

**Comment by jenstornell** [comment]
@rasteiner It also only happends when the "template switcher" is available.

**Comment by rasteiner** [comment]
It's interesting to know that the "keyCode" for F5 is 116, but "charCode 116" in ascii is "t" (lowercase T). 
Don't know if there was meant to be a short cut with "t" for the **t**emplate changer. 


See here what happens when I press F5:
![image](https://cloud.githubusercontent.com/assets/6684137/15673812/7a6e8850-2739-11e6-8645-4fc243354b30.png)

**Comment by lukasbestle** [comment]
After quite some time of tracking this down I found out that this is a bug in the jQuery hotkeys plugin:

- The Panel registers the event for key `t` as you suspected (this is done via a `data-shortcut` attribute on the link)
- The hotkeys plugin listens on key events and calls the callback if the registered key has been pressed. However it does this using [`String.fromCharCode( event.which ).toLowerCase()`](https://github.com/getkirby/panel/blob/master/assets/js/src/jquery/plugins/jquery.hotkeys.js#L73) so it uses the ASCII value instead of the key code.
- This way `F5` matches for `t` even though it shouldn't have.

We can't fix this directly in Kirby, but we will need to look for a new hotkey library. @bastianallgeier?

**Comment by jenstornell** [comment]
Do you really need a library for that? I did not need it in Splitview.

https://github.com/jenstornell/splitview/blob/master/assets/js/src/site/site.js#L51

**Comment by lukasbestle** [comment]
I did not say "framework", just "library". :)
A library for this is useful because it knows about special key codes like the f keys, backspace, escape etc.

BTW: Your code seems to have the same problem with the ASCII key codes. ;)

**Comment by manuelmoreale** [comment]
I'll leave a few suggestions for possible alternatives to the hotkeys plugin.
Since I know @bastianallgeier loves to be a "purist" of the web (and so do I) the following are pure js libraries, no jQuery involved.

Not sure if these are 100% what you guys are looking for but maybe I'll save you a few searches.

- https://github.com/ccampbell/mousetrap
- https://github.com/madrobby/keymaster
- https://github.com/jaywcjlove/hotkeys/
- https://github.com/dmauro/Keypress/

**Comment by chpio** [comment]
any progress on this one?

**Comment by lukasbestle** [comment]
Sorry for the delay! We haven't been able to fix this in Kirby 2, but as far as I can tell, Kirby 3 (which will be out soon) won't have this issue. :)
