### ISSUE TITLE
Potential data loss with multi-language version in multiple tabs

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby-v2/panel#987]

**Comment by jenstornell** [comment]
**Maybe related:**

https://github.com/getkirby/panel/issues/943

Even if it's not the same issue, it might be solved in the same way, to not store the language in the session/memory. Instead save the language on the page, as a hidden field or in the url. That way the save button can get the language from there and not rely on the memory.

**Comment by mzur** [comment]
May be related to this as well (Panel Version 2.4.1). Say we have a multi-language site with EN (default) and DE as languages:

1. Create a new page.
2. The new page is displayed in the DE version because the panel was currently switched to DE. We want to enter the EN content first so we switch to EN without entering or saving anything to the DE version.
3. Add some content to the EN version but *don't* save.
4. Switch to the DE version, add some content, *don't* save as well.
5. Switch back to EN. **The content entered in 3. will be overwritten with the content of 4.**
6. Switch back to DE. **The content entered in 4. will be erased.**

Step 2 seems to be essential here.

**Comment by lukasbestle** [comment]
The Panel does not buffer the content separately per language at the moment. This is the reason why you are seeing this behavior.
It's a separate issue, but related to this issue.

**Comment by nilsgabriel** [comment]
Is there a workaround for this? 

I have a more random behaviour that sometimes the languages are switched on save, or replaced by one language.
